#!/usr/bin/env node

var exec = require('child_process').exec;

var curlCmd = 'curl -sb -H "Accept: application/json" "http://api.icndb.com/jokes/random?firstName=Louis&lastName=Borsu"';

exec(curlCmd,{ timeout: 2500 }, function(stdErr,stdOut){
  if (!stdErr) {
    var jokeData = JSON.parse(stdOut);
    console.log(jokeData.value.joke);
  } else {
    console.log('Louis Borsu gots internet even without internet');
  }

});
